name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-west-1  # Specify the AWS region here

      - name: Pull Docker image from Docker Hub
        run: |
          docker pull gadagojushiva/my-node-app:latest

      - name: Tag Docker image for Amazon ECR
        run: |
          docker tag gadagojushiva/my-node-app:latest ${{ steps.login-ecr.outputs.registry }}/mynodejsapp:latest

      - name: Push Docker image to Amazon ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/mynodejsapp:latest

      - name: Deploy to ECS
        run: |
          aws ecs update-service --cluster my-app-cluster --service my-app-service --force-new-deployment
