name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-1
        run: aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID && aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY && aws configure set region $AWS_REGION

      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 730335353897.dkr.ecr.us-west-1.amazonaws.com

      - name: Pull Docker image
        run: docker pull gadagojushiva/my-node-app:latest

      - name: Tag Docker image for Amazon ECR
        run: docker tag gadagojushiva/my-node-app:latest 730335353897.dkr.ecr.us-west-1.amazonaws.com/mynodejsapp:latest

      - name: Push Docker image to Amazon ECR
        run: docker push 730335353897.dkr.ecr.us-west-1.amazonaws.com/mynodejsapp:latest

      - name: Deploy to ECS
        run: aws ecs update-service --cluster my-app-cluster --service my-app-service --force-new-deployment
