name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          region: us-west-1  # Specify the AWS region here

      - name: Pull Docker image from Docker Hub
        run: |
          docker pull gadagojushiva/my-node-app:latest

      - name: Push Docker image to ECR
        run: |
          docker tag gadagojushiva/my-node-app:latest <aws_account_id>.dkr.ecr.us-west-1.amazonaws.com/my-node-app:latest
          docker push 730335353897.dkr.ecr.us-west-1.amazonaws.com/my-node-app:latest

      - name: Deploy to ECS
        run: |
          aws ecs update-service --cluster my-app-cluster --service my-app-service --force-new-deployment
